development:
    jid: component.domain.com
    password: password
    host: localhost
    port: 5222

development:
    jid: component.domain.com
    password: password
    host: domain.com
    port: 5222
