# This determines the routing for your controllers
# The matching is based on XPATH

# route_name:
#   priority: if a stanza matches several XPath conditions, the one with the greater priority will be executed. If they have the same priority, one will be chose randomly, so choose your priority very carefully! It is a good practice to attribute a different priority to each of your routes, so that there is no conflict
#   controller: name of the controller that should handle the stanza
#   action: action to be called to handle the stanza
#   xpath: used to macth the stanza
#
# The namespace(node_set, node_name, namespace_uri) custom xpath expression can map stanzas based on namespace URI
# Use the following to map a service discovery query:
#   xpath: "//iq[@type='get']/*[namespace(., 'query', 'http://jabber.org/protocol/disco#info')]"
# Due to Nokogiri limitations, both the '*' and '.' are necessary.

# my_route_1:
#     priority: 1
#     controller: main
#     xpath: "//message"
#     action: echo

